name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-osx:
    name: OS X
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Test
      continue-on-error: true # this is bad, but I don't have OS X hardware to test on
      run: cargo test
  build-ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Test
      run: cargo test
  build-windows:
    name: Windows 2019 Server
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
        cmd /C ver
    - name: Install
      run: |
        rustup target add i686-pc-windows-msvc
    - name: Test
      run: scripts\build
